version: "3.8"

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx_cfg/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - apigateway
  #   networks:
  #     - app-network

  # apigateway:
  #   build: ./custom_gateway
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./custom_gateway:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: node gateway.js
  #   networks:
  #     - app-network

  # haproxy:
  #   image: haproxy:latest
  #   ports:
  #     - "8082:8082"
  #   volumes:
  #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   networks:
  #     - app-network

  # servicea:
  #   build: ./services
  #   ports:
  #     - "1111:5000"
  #   volumes:
  #     - ./services:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: node run start
  #   networks:
  #     - app-network

  serviceb:
    build: ./services
    ports:
      - "2222:5000"
    volumes:
      - ./services:/usr/src/app
    working_dir: /usr/src/app
    command: node index.js
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
