apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2  # Number of replicas (scale as needed)
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: your-docker-repo/api-gateway:latest  # Replace with your API Gateway Docker image
          ports:
            - containerPort: 8000  # Port exposed by the API Gateway
          env:
            - name: SERVICE_A_URL
              value: "http://servicea.default.svc.cluster.local:3000"  # Replace with your Service A's internal Kubernetes service URL
            - name: SERVICE_B_URL
              value: "http://serviceb.default.svc.cluster.local:3001"  # Replace with your Service B's internal Kubernetes service URL
          volumeMounts:
            - name: config-volume
              mountPath: /etc/api-gateway
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config  # If you have any configMap for dynamic configurations

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Internal service type, modify if you need external exposure

