apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
        - name: servicea
          image: servicea-image:latest
          ports:
            - containerPort: 3000